apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortune-cookies
spec:
  selector:
    matchLabels:
      app: fortune-cookies
  replicas: 1
  template:
    metadata:
      labels:
        app: fortune-cookies
    spec:
      containers:
        - name: app
          image: cc-ms-k8s-training.common.repositories.cloud.sap/fortune-cookies-i355649
          ports:
            - containerPort: 3000
          env: 
           - name: mypath
             value: postgres://postgres@fortune-cookies-db/postgres
      imagePullSecrets:
       - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: fortune-cookies
spec:
  selector:
    app: fortune-cookies
  ports:
    - name: app
      port: 3000
      targetPort: 3000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert.gardener.cloud/purpose: managed
    nginx.ingress.kubernetes.io/proxy-body-size: 150m
  name: fortune-cookies
spec:
  rules:
  - host: app.ingress.ctf.test-ks.shoot.canary.k8s-hana.ondemand.com
    http:
      paths:
      - backend:
          service:
            name: fortune-cookies
            port:
              number: 3000
        path: /
        pathType: Exact
  tls:
  - hosts:
    - app.ingress.ctf.test-ks.shoot.canary.k8s-hana.ondemand.com
    secretName: app-certs